### ISSUE TITLE
Le tutoriel ne s'affiche pas au premier lancement

### ISSUE THREAD

**Issue by Nicolapps** [RemyDCF/tpg-offline#1]
J'ai découvert l'option « Revoir le tutoriel » dans les paramètres, pourtant quand j'ai ouvert pour la première fois l'application je n'ai pas vu ce tutoriel 😛. Par contre, j'ai vu le message me proposant d'autoriser l'application à envoyer des notifications et à accéder à ma position.

**Comment by prettysunflower** [comment]
Merci, j'ai corrigé ce bug dans le commit 8d3e76f
