### ISSUE TITLE
Directions page filled with black

### ISSUE THREAD

**Issue by Nicolapps** [RemyDCF/tpg-offline#15]
Env : iPhone 6s, iOS 11.1.1, tpg offline 13

**Steps to reproduce :**
1. Open the “Itinéraires” tab
2. Search routes
3. Go to another tab
4. Go back to the directions tab. Instead of the page, a black page is shown.

It doesn't always happen, and I couldn’t find what triggers this bug.

![Screenshot](https://user-images.githubusercontent.com/7029582/33150521-2465d874-cfd4-11e7-9615-3e01da7740d2.PNG)

**Comment by prettysunflower** [comment]
Je pense que c'est résolu. La même chose que [ici](https://stackoverflow.com/questions/33291347/uisearchcontroller-causes-black-screen-swift-2-0) à du se passer.
