### ISSUE TITLE
Refresh Offline Departures freeze at 90% leads to crash

### ISSUE THREAD

**Issue by Forest14** [RemyDCF/tpg-offline#5]
Hi,
When Refresh Offline Departures is launched, the meter goes to 90%, app freezes and then crashes after ~30 seconds.

**Comment by prettysunflower** [comment]
Can I have more details? Which version of tpg offline did you used, which device, what type of internet connection, ...? And, did you have the crash report?

**Comment by Forest14** [comment]
Version 12 in English running on iOS 10.2. It fails despite excellent wifi connection.
Let me know how to extract crash report if it can help.

**Comment by prettysunflower** [comment]
You can find how to extract the crash report at [https://help.getpocket.com/article/1098-how-to-find-the-iphone-ipad-app-crash-logs](https://help.getpocket.com/article/1098-how-to-find-the-iphone-ipad-app-crash-logs). If you don't want to send it by Github, please, send it at support@dacostafaro.com

**Comment by prettysunflower** [comment]
This issue has no response since 2 months. Free feel to open again the issue if more informations are supplied
